apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gcp-secret-mattermost-config
  namespace: mattermost
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-store
  target:
    name: gcp-secret-config
    creationPolicy: Owner
  data:
  - secretKey: config.json
    remoteRef:
      key: mattermost-config
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gcp-secret-mattermost-license
  namespace: mattermost
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-store
  target:
    name: gcp-secret-license
    creationPolicy: Owner
  data:
  - secretKey: mitoujr.mattermost-license
    remoteRef:
      key: mattermost-license
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gcp-secret-mattermost-env
  namespace: mattermost
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-store
  target:
    name: gcp-secret-env
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: mattermost-env
