apiVersion: apps/v1
kind: Deployment
metadata:
  name: mattermost
  namespace: mattermost
  labels:
    app: mattermost
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  replicas: 1
  selector:
    matchLabels:
      app: mattermost
  template:
    metadata:
      labels:
        app: mattermost
    spec:
      serviceAccountName: mattermost-primary
      initContainers:
        - name: secret-placer
          image: gcr.io/google.com/cloudsdktool/cloud-sdk:latest
          command: ["/bin/sh","-c"]
          args:
            - gcloud kms decrypt --location asia-northeast1 --keyring primary-keyring --key primary-key --ciphertext-file=/secret/config.json --plaintext-file=/config/config.json
              && chmod o+w /config/config.json
          volumeMounts:
            - name: config
              mountPath: /config
            - name: secret
              mountPath: /secret
      containers:
      - name: mattermost
        image: mattermost/mattermost-team-edition:release-7.9
        ports:
        - containerPort: 8000
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 1Gi
        volumeMounts:
          - name: config
            mountPath: /mattermost/config/
      volumes:
        - name: config
          emptyDir: {}
        - name: secret
          secret:
            secretName: secret-configs
