apiVersion: apps/v1
kind: Deployment
metadata:
  name: mattermost
  namespace: mattermost
  labels:
    app: mattermost
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  replicas: 1
  selector:
    matchLabels:
      app: mattermost
  template:
    metadata:
      labels:
        app: mattermost
    spec:
      securityContext: 
        fsGroup: 2000
      serviceAccountName: mattermost-primary
      initContainers:
        - name: secret-placer
          image: gcr.io/google.com/cloudsdktool/cloud-sdk:latest
          command: ["/bin/sh","-c"]
          args:
            - gcloud kms decrypt --location asia-northeast1 --keyring primary-keyring --key primary-key --ciphertext-file=/secret/config.json --plaintext-file=/config/config.json
              && chown 2000:2000 /config/config.json
          volumeMounts:
            - name: config
              mountPath: /config
            - name: secret
              mountPath: /secret
      containers:
      - name: mattermost
        image: mattermost/mattermost-team-edition:release-9.1
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8000
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 2Gi
        readinessProbe:
          timeoutSeconds: 5
          periodSeconds: 5
          failureThreshold: 4
          httpGet:
            path:  /api/v4/system/ping
            port: http
        livenessProbe:
          initialDelaySeconds: 600
          timeoutSeconds: 5
          periodSeconds: 15
          failureThreshold: 4
          httpGet:
            path:  /api/v4/system/ping
            port: http
        startupProbe:
          httpGet:
            path:  /api/v4/system/ping
            port: http
          failureThreshold: 8640
          periodSeconds: 10
        volumeMounts:
          - name: config
            mountPath: /mattermost/config/
          - name: bleve-cache
            mountPath: /mattermost/bleve/
      volumes:
        - name: config
          emptyDir: {}
        - name: secret
          secret:
            secretName: secret-configs
        - name: bleve-cache
          persistentVolumeClaim:
            claimName: mattermost-bleve-pvc
