apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mattermost-bleve-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard-rwo