apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcp-secret-store
  namespace: mattermost
spec:
  provider:
    gcpsm:
      projectID: mitou-jr
      auth:
        workloadIdentity:
          clusterLocation: asia-northeast1
          clusterName: primary-cluster
          serviceAccountRef:
            name: external-secrets
            namespace: default
