apiVersion: v1
kind: Service
metadata:
  name: mattermost
  namespace: mattermost
  annotations:
    cloud.google.com/neg: '{"exposed_ports": {"8000":{"name": "mattermost"}}}'
spec:
  type: ClusterIP
  selector:
    app: mattermost
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000